version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
    timezone: Etc/UCT
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: husky
    versions:
    - ">=5.0.0"
  - dependency-name: yargs*
    versions:
    - ">= 0"
  - dependency-name: contentful-migration
    versions:
    - 4.0.10
    - 4.0.12
    - 4.0.13
    - 4.0.9
    - 4.1.1
    - 4.1.3
  - dependency-name: contentful-import
    versions:
    - 7.9.40
    - 7.9.41
    - 7.9.42
    - 8.0.0
    - 8.0.1
    - 8.0.2
    - 8.0.3
    - 8.0.4
    - 8.0.5
    - 8.0.6
    - 8.1.1
    - 8.1.2
  - dependency-name: contentful-management
    versions:
    - 7.10.0
    - 7.11.0
    - 7.13.1
    - 7.15.2
    - 7.9.0
  - dependency-name: marked
    versions:
    - 1.2.8
    - 1.2.9
    - 2.0.3
  - dependency-name: contentful-export
    versions:
    - 7.11.10
    - 7.11.11
    - 7.11.12
    - 7.11.15
    - 7.11.16
    - 7.11.18
    - 7.11.9
    - 7.12.1
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.8
    - 24.2.0
    - 24.2.1
    - 24.3.1
    - 24.3.3
    - 24.3.4
  - dependency-name: open
    versions:
    - 7.4.1
    - 8.0.1
    - 8.0.2
    - 8.0.3
    - 8.0.4
  - dependency-name: eslint
    versions:
    - 7.22.0
  registries:
  - npm-registry-registry-npmjs-org
